name = input(" What is your name?")
print(f" ~ Hello {name}, welcome to Jokes.py ")
print(" ~ Ready for some EGG-salent jokes?")
input()
print(" ~ How do chickens stay fit?")
input()
print(" ~ They eggs-ercise")
input()
print(" ~ Why do you have to watch what your saying around the egg whites?")
input()
print(" ~ They can't take a yolk")
input()
print(" ~ Why do you have to watch what your saying around me?")
input()
print(" ~ What's an eggs least fav day?")
input()
print(" ~ Fry-day")
input()
print(" ~ Hehehe")
print(" ~ Hope your laughing")
input()
print(f" ~ Are you having fun {name}?")
print(f" ~ {name}!")
print(f" ~ {name}!")
print(f" ~ {name}!")
input()
print("  I know your name now")
print(f" ~ {name}!")
print(f" ~ {name}!")
input()
print(f" ~ {name}!")
print(" ~ I hope you stay with me forever")