print(" BOOTING UP PRESS ENTER TO START")
input()
print(".")
print(".")
print(".")
print("~ Hello!")
print("~ I am project1.py")
print("~ What is your name?")
name = input()
print(f"~ Hello {name}!")
print("~ How are you?")
emotion = input()
print(f"~ I'm {emotion} too.")
print("~ In this project you dodge obstacles")
print("~ You must do this: ")
print("~ INPUT a single line ! <-- like this one, also add spaces to dodge. Practice below")
input()
print("    ______     _____________ __ ____________")
print("~ Yayyyy! Did you make it? If not thats okay!")
input()
print("~ Now lets put you to the test! If you don't make, just move on with the program!")
print("STARTING GAME STAND BY")
input("press enter                       put spaces and line on next one")
input()
print("____  _______        __  ____ _____       ___")
input(" LEVEL 1 COMPLETE STARTING LEVEL 2")
input()
print("      _______   __ ______      ____     ___ _")
input(" LEVEL 2 COMPLETE STARTING LEVEL 3")
input()
print("_____ _______   _________________  ___    ___")
input(" LEVEL 3 COMPLETE STARTING LEVEL 4")
input()
print("_______   __________  _____ __________   ____")
input(" LEVEL 4 COMPLETE STARTING LEVEL 5")
input()
print("_____  _________ __________   ______ __ _____")
input(" LEVEL 5 COMPLETE STARTING LEVEL 6")
input()
print("____ ____ _____ ____ _________ _____ ______ _")
input(" LEVEL 6 COMPLETE STARTING LEVEL 7")
input()
print("_______ __________   _________   _________  _")
input(" LEVEL 7 COMPLETE STARTING LEVEL 8")
input()
print("______________        _____________ _________")
input(" LEVEL 8 COMPLETE STARTING LEVEL 9")
input()
print("_____________ ___________________ ____ ______")
input(" LEVEL 9 COMPLTETE")
print(f"~ Thank you for playing {name}! More levels coming soon!")
